config/routes.rb
Rails.application.routes.draw do
  resources :extractor_templates
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/extractor_template.rb
class ExtractorTemplate < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/extractor_templates_controller.rb
class ExtractorTemplatesController < ApplicationController
  before_action :set_extractor_template, only: %i[ show edit update destroy ]

  # GET /extractor_templates or /extractor_templates.json
  def index
    @extractor_templates = ExtractorTemplate.all
  end

  # GET /extractor_templates/1 or /extractor_templates/1.json
  def show
  end

  # GET /extractor_templates/new
  def new
    @extractor_template = ExtractorTemplate.new
  end

  # GET /extractor_templates/1/edit
  def edit
  end

  # POST /extractor_templates or /extractor_templates.json
  def create
    @extractor_template = ExtractorTemplate.new(extractor_template_params)

    respond_to do |format|
      if @extractor_template.save
        ::ExtractorTemplates::CreateGithubIssue.perform
        format.html { redirect_to @extractor_template, notice: "Extractor template was successfully created." }
        format.json { render :show, status: :created, location: @extractor_template }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @extractor_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /extractor_templates/1 or /extractor_templates/1.json
  def update
    respond_to do |format|
      if @extractor_template.update(extractor_template_params)
        format.html { redirect_to @extractor_template, notice: "Extractor template was successfully updated." }
        format.json { render :show, status: :ok, location: @extractor_template }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @extractor_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /extractor_templates/1 or /extractor_templates/1.json
  def destroy
    @extractor_template.destroy
    respond_to do |format|
      format.html { redirect_to extractor_templates_url, notice: "Extractor template was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_extractor_template
      @extractor_template = ExtractorTemplate.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def extractor_template_params
      params.require(:extractor_template).permit(:sheetID, :SheetName, :PrimaryKey)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/extractor_templates_helper.rb
module ExtractorTemplatesHelper
end

app/views/extractor_templates/_form.html.erb
<%= form_with(model: extractor_template, local: true) do |form| %>
  <% if extractor_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(extractor_template.errors.count, "error") %> prohibited this extractor_template from being saved:</h2>

      <ul>
      <% extractor_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :sheetID %>
    <%= form.text_field :sheetID %>
  </div>

  <div class="field">
    <%= form.label :SheetName %>
    <%= form.text_field :SheetName %>
  </div>

  <div class="field">
    <%= form.label :PrimaryKey %>
    <%= form.text_field :PrimaryKey %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/extractor_templates/edit.html.erb
<h1>Editing Extractor Template</h1>

<%= render 'form', extractor_template: @extractor_template %>

<%= link_to 'Show', @extractor_template %> |
<%= link_to 'Back', extractor_templates_path %>

app/views/extractor_templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Extractor Templates</h1>

<table>
  <thead>
    <tr>
      <th> sheetid</th>
      <th>Sheetname</th>
      <th>Primarykey</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @extractor_templates.each do |extractor_template| %>
      <tr>
        <td><%= extractor_template.sheetID %></td>
        <td><%= extractor_template.SheetName %></td>
        <td><%= extractor_template.PrimaryKey %></td>
        <td><%= link_to 'Show', extractor_template %></td>
        <td><%= link_to 'Edit', edit_extractor_template_path(extractor_template) %></td>
        <td><%= link_to 'Destroy', extractor_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Extractor Template', new_extractor_template_path %>

app/views/extractor_templates/new.html.erb
<h1>New Extractor Template</h1>

<%= render 'form', extractor_template: @extractor_template %>

<%= link_to 'Back', extractor_templates_path %>

app/views/extractor_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> sheetid:</strong>
  <%= @extractor_template. sheetID %>
</p>

<p>
  <strong>Sheetname:</strong>
  <%= @extractor_template.SheetName %>
</p>

<p>
  <strong>Primarykey:</strong>
  <%= @extractor_template.PrimaryKey %>
</p>

<%= link_to 'Edit', edit_extractor_template_path(@extractor_template) %> |
<%= link_to 'Back', extractor_templates_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Extractor</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>